/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import model.bean.Clientes;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Fornecedores;
import model.dao.ClienteDao;
import model.dao.FornecedorDao;

/**
 *
 * @author Naine
 */
public class TelaManterClientes extends javax.swing.JFrame {
    
    Clientes cliente = new Clientes();
    ClienteDao dao = new ClienteDao();
    
    public TelaManterClientes() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jCliente.getModel();
        jCliente.setRowSorter(new TableRowSorter(modelo));
        readjTable();
    }
    public void readjTable() {
        DefaultTableModel modelo = (DefaultTableModel) jCliente.getModel();
        modelo.setNumRows(0);
        ClienteDao cdao = new ClienteDao();

        for (Clientes c : cdao.read()) {

            modelo.addRow(new Object[]{
                c.getCod_cliente(),
                c.getNome_cliente(),
                c.getCnpj(),
            
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_cliente_nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_cliente_cod = new javax.swing.JTextField();
        jButton_cadastrar_cliente = new javax.swing.JButton();
        jButton_alterar_cliente = new javax.swing.JButton();
        jButton_excluir_cliente = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jCliente = new javax.swing.JTable();
        txt_cliente_cnpj = new javax.swing.JFormattedTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText(" EPOS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("CADASTRAR CLIENTES");

        jLabel3.setText("Nome:");

        jLabel4.setText("CNPJ:");

        jLabel5.setText("Código");

        jButton_cadastrar_cliente.setBackground(new java.awt.Color(102, 102, 255));
        jButton_cadastrar_cliente.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cadastrar_cliente.setText("Cadastrar");
        jButton_cadastrar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cadastrar_clienteActionPerformed(evt);
            }
        });

        jButton_alterar_cliente.setBackground(new java.awt.Color(102, 102, 255));
        jButton_alterar_cliente.setForeground(new java.awt.Color(255, 255, 255));
        jButton_alterar_cliente.setText("Alterar");
        jButton_alterar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_alterar_clienteActionPerformed(evt);
            }
        });

        jButton_excluir_cliente.setBackground(new java.awt.Color(102, 0, 0));
        jButton_excluir_cliente.setForeground(new java.awt.Color(255, 255, 255));
        jButton_excluir_cliente.setText("Excluir");
        jButton_excluir_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_excluir_clienteActionPerformed(evt);
            }
        });

        jButton4.setForeground(new java.awt.Color(240, 240, 240));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/home (1).png"))); // NOI18N
        jButton4.setAlignmentY(0.0F);
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton4.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton4.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton4.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jCliente.setForeground(new java.awt.Color(0, 0, 0));
        jCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOME", "CNPJ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCliente.setName(""); // NOI18N
        jCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jClienteMouseClicked(evt);
            }
        });
        jCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jClienteKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jCliente);

        try {
            txt_cliente_cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cliente_cnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cliente_cnpjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cliente_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cliente_cnpj)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cliente_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_cadastrar_cliente)
                        .addGap(53, 53, 53)
                        .addComponent(jButton_alterar_cliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_excluir_cliente)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_cliente_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txt_cliente_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_cliente_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_excluir_cliente)
                    .addComponent(jButton_alterar_cliente)
                    .addComponent(jButton_cadastrar_cliente))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cadastrar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cadastrar_clienteActionPerformed
        cliente.setNome_cliente(txt_cliente_nome.getText());
        cliente.setCnpj(txt_cliente_cnpj.getText());
        cliente.setCod_cliente(txt_cliente_cod.getText());
        
        dao.create(cliente);
        
        txt_cliente_cnpj.setText("");
        txt_cliente_cod.setText("");
        txt_cliente_nome.setText("");
        
        readjTable();
        
        //Criei esse JOption.Pane apenas para testar se está funcionando certo, pode excluir
       // JOptionPane.showMessageDialog(null, "Cliente: " + cliente.getNome_cliente() + "\n" + "Cadastrado!");
    }//GEN-LAST:event_jButton_cadastrar_clienteActionPerformed

    private void jButton_alterar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_alterar_clienteActionPerformed
       if (jCliente.getSelectedRow() != -1){
       cliente.setNome_cliente(txt_cliente_nome.getText());
        cliente.setCnpj(txt_cliente_cnpj.getText());
        cliente.setCod_cliente(txt_cliente_cod.getText());
        
        dao.update(cliente);
        
        txt_cliente_cnpj.setText("");
        txt_cliente_cod.setText("");
        txt_cliente_nome.setText("");
        
        readjTable();
       
       }
        
        //Criei esse JOption.Pane apenas para testar se está funcionando certo, pode excluir
        //JOptionPane.showMessageDialog(null, "Cliente: " + cliente.getNome_cliente() + "\n" + "Alterado!");
    }//GEN-LAST:event_jButton_alterar_clienteActionPerformed

    private void jButton_excluir_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_excluir_clienteActionPerformed
        if (jCliente.getSelectedRow() != -1){
        cliente.setCod_cliente(txt_cliente_cod.getText());
        dao.delete(cliente);
        
        txt_cliente_cnpj.setText("");
        txt_cliente_cod.setText("");
        txt_cliente_nome.setText("");
        
        readjTable();
        
        }

//Criei esse JOption.Pane apenas para testar se está funcionando certo, pode excluir
        //JOptionPane.showMessageDialog(null, "Cliente: " + cliente.getNome_cliente() + "\n" + "Excluído!");
    }//GEN-LAST:event_jButton_excluir_clienteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new TelaMenu().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClienteMouseClicked
        if (jCliente.getSelectedRow() != -1) {

            txt_cliente_cod.setText(jCliente.getValueAt(jCliente.getSelectedRow(), 0).toString());
            txt_cliente_nome.setText(jCliente.getValueAt(jCliente.getSelectedRow(), 1).toString());
            txt_cliente_cnpj.setText(jCliente.getValueAt(jCliente.getSelectedRow(), 2).toString());
           

        }
    }//GEN-LAST:event_jClienteMouseClicked

    private void jClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jClienteKeyReleased
      if (jCliente.getSelectedRow() != -1) {

            txt_cliente_cod.setText(jCliente.getValueAt(jCliente.getSelectedRow(), 0).toString());
            txt_cliente_nome.setText(jCliente.getValueAt(jCliente.getSelectedRow(), 1).toString());
            txt_cliente_cnpj.setText(jCliente.getValueAt(jCliente.getSelectedRow(), 2).toString());
           

        }
    }//GEN-LAST:event_jClienteKeyReleased

    private void txt_cliente_cnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cliente_cnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cliente_cnpjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaManterClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaManterClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaManterClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaManterClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaManterClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_alterar_cliente;
    private javax.swing.JButton jButton_cadastrar_cliente;
    private javax.swing.JButton jButton_excluir_cliente;
    private javax.swing.JTable jCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JFormattedTextField txt_cliente_cnpj;
    private javax.swing.JTextField txt_cliente_cod;
    private javax.swing.JTextField txt_cliente_nome;
    // End of variables declaration//GEN-END:variables
}
