/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;


import javax.swing.JOptionPane;
import model.bean.Usuario;


/**
 *
 * @author Naine
 */
public class TelaMenu extends javax.swing.JFrame {
    Usuario u = new Usuario();

    /**
     * Creates new form MenuUsuarioPadrao
     */
    public TelaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_menu_produtos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_menu_categorias = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton_menu_estoque = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton_menu_relatorios = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton_menu_fornecedor = new javax.swing.JButton();
        jButton_menu_clientes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton_menu_manterusuario = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton_menu_compras = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setType(java.awt.Window.Type.POPUP);

        jButton_menu_produtos.setForeground(new java.awt.Color(60, 63, 65));
        jButton_menu_produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/zipper (2).png"))); // NOI18N
        jButton_menu_produtos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_menu_produtos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_menu_produtos.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton_menu_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_produtosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("MENU");

        jLabel3.setText("Produtos");

        jLabel4.setText("Clientes");

        jLabel5.setText("Categorias");

        jButton_menu_categorias.setForeground(new java.awt.Color(60, 63, 65));
        jButton_menu_categorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cardapio (1).png"))); // NOI18N
        jButton_menu_categorias.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_menu_categorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_menu_categorias.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton_menu_categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_categoriasActionPerformed(evt);
            }
        });

        jLabel6.setText("Saída Estoque");

        jButton_menu_estoque.setForeground(new java.awt.Color(60, 63, 65));
        jButton_menu_estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/caixa-de-entrega (1).png"))); // NOI18N
        jButton_menu_estoque.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_menu_estoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_menu_estoque.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton_menu_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_estoqueActionPerformed(evt);
            }
        });

        jLabel7.setText("Relatorios");

        jButton_menu_relatorios.setForeground(new java.awt.Color(60, 63, 65));
        jButton_menu_relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/jornal (1).png"))); // NOI18N
        jButton_menu_relatorios.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_menu_relatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_menu_relatorios.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton_menu_relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_relatoriosActionPerformed(evt);
            }
        });

        jLabel8.setText("Fornecedor");

        jButton_menu_fornecedor.setForeground(new java.awt.Color(60, 63, 65));
        jButton_menu_fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/service (1).png"))); // NOI18N
        jButton_menu_fornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_menu_fornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_menu_fornecedor.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton_menu_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_fornecedorActionPerformed(evt);
            }
        });

        jButton_menu_clientes.setForeground(new java.awt.Color(60, 63, 65));
        jButton_menu_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/customer (1).png"))); // NOI18N
        jButton_menu_clientes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_menu_clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_menu_clientes.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton_menu_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_clientesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("EPOS");

        jButton_menu_manterusuario.setForeground(new java.awt.Color(60, 63, 65));
        jButton_menu_manterusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/seguidor (1).png"))); // NOI18N
        jButton_menu_manterusuario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_menu_manterusuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_menu_manterusuario.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton_menu_manterusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_manterusuarioActionPerformed(evt);
            }
        });

        jLabel9.setText("Usuários");

        jLabel10.setText("Estoque");

        jButton_menu_compras.setForeground(new java.awt.Color(60, 63, 65));
        jButton_menu_compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/caixa-de-entrega (1).png"))); // NOI18N
        jButton_menu_compras.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_menu_compras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_menu_compras.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton_menu_compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_comprasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel3)
                                .addGap(51, 51, 51))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_menu_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jButton_menu_produtos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_menu_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_menu_compras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10))))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jButton_menu_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5)
                                    .addComponent(jButton_menu_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_menu_manterusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel9)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_menu_relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(229, 229, 229))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton_menu_produtos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_menu_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_menu_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton_menu_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton_menu_compras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel10))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton_menu_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_menu_manterusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_menu_relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_menu_manterusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_manterusuarioActionPerformed

            new TelaCadastrarUsuario().setVisible(true);
    }//GEN-LAST:event_jButton_menu_manterusuarioActionPerformed

    private void jButton_menu_categoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_categoriasActionPerformed

            new TelaManterCategorias().setVisible(true);
    }//GEN-LAST:event_jButton_menu_categoriasActionPerformed

    private void jButton_menu_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_produtosActionPerformed

        
            new TelaManterProdutos().setVisible(true);

     
    }//GEN-LAST:event_jButton_menu_produtosActionPerformed

    private void jButton_menu_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_clientesActionPerformed
       
             new TelaManterClientes().setVisible(true);
        
    }//GEN-LAST:event_jButton_menu_clientesActionPerformed

    private void jButton_menu_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_estoqueActionPerformed
        new TelaSaidaEstoque().setVisible(true);
    }//GEN-LAST:event_jButton_menu_estoqueActionPerformed

    private void jButton_menu_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_fornecedorActionPerformed

            new TelaManterFornecedor().setVisible(true);
    }//GEN-LAST:event_jButton_menu_fornecedorActionPerformed

    private void jButton_menu_relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_relatoriosActionPerformed
        new TelaRelatorios().setVisible(true);
    }//GEN-LAST:event_jButton_menu_relatoriosActionPerformed

    private void jButton_menu_comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_comprasActionPerformed
        new TelaEntradaEstoque().setVisible(true);
    }//GEN-LAST:event_jButton_menu_comprasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_menu_categorias;
    private javax.swing.JButton jButton_menu_clientes;
    private javax.swing.JButton jButton_menu_compras;
    private javax.swing.JButton jButton_menu_estoque;
    private javax.swing.JButton jButton_menu_fornecedor;
    private javax.swing.JButton jButton_menu_manterusuario;
    private javax.swing.JButton jButton_menu_produtos;
    private javax.swing.JButton jButton_menu_relatorios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
