/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Armazenamento;
import model.bean.Clientes;
import model.bean.Saida;
import model.dao.ArmazenamentoDao;
import model.dao.ClienteDao;
import model.dao.SaidaDao;

/**
 *
 * @author Naine
 */
public class TelaSaidaEstoque extends javax.swing.JFrame {

    Saida saida = new Saida();
    Armazenamento armazenamento = new Armazenamento();
    ArmazenamentoDao adao = new ArmazenamentoDao();
    SaidaDao dao= new SaidaDao();
    public TelaSaidaEstoque() {
        initComponents();
        
        ArmazenamentoDao adao =new ArmazenamentoDao();
    for (Armazenamento a : adao.read()) {
        jComboBox_armazenamento.addItem(a);
        }
    ClienteDao cdao =new ClienteDao();
    for (Clientes c : cdao.read()) {
        jComboBox_cliente.addItem(c);
        }
    DefaultTableModel modelo = (DefaultTableModel) jSaida.getModel();
        jSaida.setRowSorter(new TableRowSorter(modelo));
        readjTable();
    }
     public void readjTable() {
        DefaultTableModel modelo = (DefaultTableModel) jSaida.getModel();
        modelo.setNumRows(0);
       
        SaidaDao sdao = new SaidaDao();

        for (Saida s : sdao.read()) {

            modelo.addRow(new Object[]{
                s.getCod_saida(),
                s.getArmazenamento(),
                s.getCliente(),
                s.getQtd(),
                s.getData(),
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jArmazenamento = new javax.swing.JTable();
        jButton_pedido = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_cod_saida = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_qtd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jComboBox_armazenamento = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox_cliente = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jSaida = new javax.swing.JTable();
        txt_data = new javax.swing.JFormattedTextField();
        jButton_saida1 = new javax.swing.JButton();

        jArmazenamento.setForeground(new java.awt.Color(0, 0, 0));
        jArmazenamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "PRODUTO", "FORNECEDOR", "QUANTIDADE", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jArmazenamento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jArmazenamento.setName(""); // NOI18N
        jArmazenamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jArmazenamentoMouseClicked(evt);
            }
        });
        jArmazenamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jArmazenamentoKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jArmazenamento);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jButton_pedido.setBackground(new java.awt.Color(102, 102, 255));
        jButton_pedido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_pedido.setForeground(new java.awt.Color(255, 255, 255));
        jButton_pedido.setText("SOLICITAR PEDIDO");
        jButton_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pedidoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Quantidade:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Data:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setText("EPOS");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("SAÍDA DO ESTOQUE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Código:");

        jButton5.setForeground(new java.awt.Color(240, 240, 240));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/home (1).png"))); // NOI18N
        jButton5.setAlignmentY(0.0F);
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusPainted(false);
        jButton5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton5.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton5.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton5.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBox_armazenamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_armazenamentoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Estoque:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Cliente:");

        jComboBox_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_clienteActionPerformed(evt);
            }
        });

        jSaida.setForeground(new java.awt.Color(0, 0, 0));
        jSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "ESTOQUE", "CLIENTE", "QUANTIDADE", "DATA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jSaida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSaida.setName(""); // NOI18N
        jSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSaidaMouseClicked(evt);
            }
        });
        jSaida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSaidaKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jSaida);

        try {
            txt_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton_saida1.setBackground(new java.awt.Color(102, 102, 255));
        jButton_saida1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_saida1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_saida1.setText("BAIXA");
        jButton_saida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saida1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(27, 27, 27)
                                    .addComponent(jComboBox_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(25, 25, 25)
                                    .addComponent(txt_cod_saida, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox_armazenamento, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(jButton_saida1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_pedido)
                        .addGap(200, 200, 200))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_cod_saida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox_armazenamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jButton_saida1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_pedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new TelaMenu().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox_armazenamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_armazenamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_armazenamentoActionPerformed

    private void jComboBox_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_clienteActionPerformed

    private void jButton_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pedidoActionPerformed
            new TelaPedidos().setVisible(true);       
    }//GEN-LAST:event_jButton_pedidoActionPerformed

    private void jArmazenamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jArmazenamentoMouseClicked
       
    }//GEN-LAST:event_jArmazenamentoMouseClicked

    private void jArmazenamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jArmazenamentoKeyReleased
       
            
    }//GEN-LAST:event_jArmazenamentoKeyReleased

    private void jSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSaidaMouseClicked
       if (jSaida.getSelectedRow() != -1) {

            txt_cod_saida.setText(jSaida.getValueAt(jSaida.getSelectedRow(), 0).toString());
            jComboBox_armazenamento.setSelectedItem(jSaida.getValueAt(jSaida.getSelectedRow(), 1).toString());
            jComboBox_cliente.setSelectedItem(jSaida.getValueAt(jSaida.getSelectedRow(), 2).toString());
            txt_qtd.setText(jSaida.getValueAt(jSaida.getSelectedRow(), 3).toString());
            txt_data.setText(jSaida.getValueAt(jSaida.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_jSaidaMouseClicked

    private void jSaidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSaidaKeyReleased
       if (jSaida.getSelectedRow() != -1) {

            txt_cod_saida.setText(jSaida.getValueAt(jSaida.getSelectedRow(), 0).toString());
            jComboBox_armazenamento.setSelectedItem(jSaida.getValueAt(jSaida.getSelectedRow(), 1).toString());
            jComboBox_cliente.setSelectedItem(jSaida.getValueAt(jSaida.getSelectedRow(), 2).toString());
            txt_qtd.setText(jSaida.getValueAt(jSaida.getSelectedRow(), 3).toString());
            txt_data.setText(jSaida.getValueAt(jSaida.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_jSaidaKeyReleased

    private void jButton_saida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saida1ActionPerformed
       saida.setCod_saida(txt_cod_saida.getText());
       saida.setArmazenamento((Armazenamento) jComboBox_armazenamento.getSelectedItem());
       saida.setCliente((Clientes) jComboBox_cliente.getSelectedItem());
       saida.setData(txt_data.getText());
       saida.setQtd(Integer.parseInt(txt_qtd.getText()));
        try {
            saida.ConferirEstoque();
            dao.create(saida);
            JOptionPane.showMessageDialog(null, "Favor, atualizar o valor do armazenamento");
            new TelaEntradaEstoque().setVisible(true);
            
       
            //AtualizaArmazenamento();
        } catch (Exception ex) {
            Logger.getLogger(TelaSaidaEstoque.class.getName()).log(Level.SEVERE, null, ex);
        }
       

       txt_cod_saida.setText("");
       txt_data.setText("");
       txt_qtd.setText("");
        
       readjTable();
    }//GEN-LAST:event_jButton_saida1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSaidaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSaidaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSaidaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSaidaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSaidaEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jArmazenamento;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton_pedido;
    private javax.swing.JButton jButton_saida1;
    private javax.swing.JComboBox<Object> jComboBox_armazenamento;
    private javax.swing.JComboBox<Object> jComboBox_cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTable jSaida;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txt_cod_saida;
    private javax.swing.JFormattedTextField txt_data;
    private javax.swing.JTextField txt_qtd;
    // End of variables declaration//GEN-END:variables
}
