/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import static model.bean.Armazenamento.gerarPdfEstoque;
import static model.bean.Categorias.gerarPdfCategorias;
import static model.bean.Clientes.gerarPdfClientes;
import static model.bean.Fornecedores.gerarPdfFornecedores;
import static model.bean.Pedidos.gerarPdfPedido;
import model.bean.Produtos;
import static model.bean.Produtos.gerarPdfProduto;
import static model.bean.Saida.gerarPdfsSaida;
import static model.bean.Usuario.gerarPdfUsuarios;

/**
 *
 * @author Naine
 */
public class TelaRelatorios extends javax.swing.JFrame {
    //teste tela relatorio
    /**
     * Creates new form TelaRelatorioCompras
     */
    public TelaRelatorios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton_menu_compras = new javax.swing.JButton();
        jButton_menu_estoque = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton_menu_produtos = new javax.swing.JButton();
        jButton_menu_fornecedor = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton_menu_clientes = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_menu_categorias = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton_menu_manterusuario = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton_menu_compras1 = new javax.swing.JButton();
        jButton_menu_estoque1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton_menu_relatorios = new javax.swing.JButton();

        jLabel10.setText("Estoque");

        jLabel6.setText("Saída Estoque");

        jButton_menu_compras.setForeground(new java.awt.Color(60, 63, 65));
        jButton_menu_compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/caixa-de-entrega (1).png"))); // NOI18N
        jButton_menu_compras.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_menu_compras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_menu_compras.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton_menu_compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_comprasActionPerformed(evt);
            }
        });

        jButton_menu_estoque.setForeground(new java.awt.Color(60, 63, 65));
        jButton_menu_estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/caixa-de-entrega (1).png"))); // NOI18N
        jButton_menu_estoque.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_menu_estoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_menu_estoque.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton_menu_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_estoqueActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("RELATÓRIOS");

        jButton6.setForeground(new java.awt.Color(240, 240, 240));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/home (1).png"))); // NOI18N
        jButton6.setAlignmentY(0.0F);
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusPainted(false);
        jButton6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton6.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton6.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton6.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel3.setText("Produtos");

        jButton_menu_produtos.setForeground(new java.awt.Color(60, 63, 65));
        jButton_menu_produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/zipper (2).png"))); // NOI18N
        jButton_menu_produtos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_menu_produtos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_menu_produtos.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton_menu_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_produtosActionPerformed(evt);
            }
        });

        jButton_menu_fornecedor.setForeground(new java.awt.Color(60, 63, 65));
        jButton_menu_fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/service (1).png"))); // NOI18N
        jButton_menu_fornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_menu_fornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_menu_fornecedor.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton_menu_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_fornecedorActionPerformed(evt);
            }
        });

        jLabel8.setText("Fornecedor");

        jButton_menu_clientes.setForeground(new java.awt.Color(60, 63, 65));
        jButton_menu_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/customer (1).png"))); // NOI18N
        jButton_menu_clientes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_menu_clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_menu_clientes.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton_menu_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_clientesActionPerformed(evt);
            }
        });

        jLabel4.setText("Clientes");

        jLabel5.setText("Categorias");

        jButton_menu_categorias.setForeground(new java.awt.Color(60, 63, 65));
        jButton_menu_categorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cardapio (1).png"))); // NOI18N
        jButton_menu_categorias.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_menu_categorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_menu_categorias.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton_menu_categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_categoriasActionPerformed(evt);
            }
        });

        jLabel9.setText("Usuários");

        jButton_menu_manterusuario.setForeground(new java.awt.Color(60, 63, 65));
        jButton_menu_manterusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/seguidor (1).png"))); // NOI18N
        jButton_menu_manterusuario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_menu_manterusuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_menu_manterusuario.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton_menu_manterusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_manterusuarioActionPerformed(evt);
            }
        });

        jLabel11.setText("Estoque");

        jLabel7.setText("Saída ");

        jButton_menu_compras1.setForeground(new java.awt.Color(60, 63, 65));
        jButton_menu_compras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/caixa-de-entrega (1).png"))); // NOI18N
        jButton_menu_compras1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_menu_compras1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_menu_compras1.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton_menu_compras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_compras1ActionPerformed(evt);
            }
        });

        jButton_menu_estoque1.setForeground(new java.awt.Color(60, 63, 65));
        jButton_menu_estoque1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/caixa-de-entrega (1).png"))); // NOI18N
        jButton_menu_estoque1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_menu_estoque1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_menu_estoque1.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton_menu_estoque1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_estoque1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("EPOS");

        jLabel12.setText("Pedidos");

        jButton_menu_relatorios.setForeground(new java.awt.Color(60, 63, 65));
        jButton_menu_relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/jornal (1).png"))); // NOI18N
        jButton_menu_relatorios.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton_menu_relatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_menu_relatorios.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton_menu_relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_relatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(68, 68, 68)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton_menu_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                    .addGap(58, 58, 58)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton_menu_compras1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel11)))
                                    .addGap(57, 57, 57)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton_menu_estoque1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(jLabel7)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton_menu_relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel12))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(74, 74, 74)
                                            .addComponent(jLabel3)
                                            .addGap(57, 57, 57))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(68, 68, 68)
                                            .addComponent(jButton_menu_produtos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(55, 55, 55)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton_menu_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel4)))
                                    .addGap(51, 51, 51)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(jButton_menu_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel5))
                                    .addGap(51, 51, 51)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton_menu_manterusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jLabel9))))))
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_menu_produtos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel5))
                            .addComponent(jButton_menu_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton_menu_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton_menu_manterusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton_menu_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton_menu_compras1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel11))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton_menu_estoque1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_menu_relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new TelaMenu().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton_menu_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_produtosActionPerformed
        gerarPdfProduto();

    }//GEN-LAST:event_jButton_menu_produtosActionPerformed

    private void jButton_menu_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_fornecedorActionPerformed

        gerarPdfFornecedores();
    }//GEN-LAST:event_jButton_menu_fornecedorActionPerformed

    private void jButton_menu_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_clientesActionPerformed

       gerarPdfClientes();

    }//GEN-LAST:event_jButton_menu_clientesActionPerformed

    private void jButton_menu_categoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_categoriasActionPerformed
         gerarPdfCategorias();
    }//GEN-LAST:event_jButton_menu_categoriasActionPerformed

    private void jButton_menu_manterusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_manterusuarioActionPerformed

        gerarPdfUsuarios();
    }//GEN-LAST:event_jButton_menu_manterusuarioActionPerformed

    private void jButton_menu_comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_comprasActionPerformed
        new TelaEntradaEstoque().setVisible(true);
    }//GEN-LAST:event_jButton_menu_comprasActionPerformed

    private void jButton_menu_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_estoqueActionPerformed
        new TelaSaidaEstoque().setVisible(true);
    }//GEN-LAST:event_jButton_menu_estoqueActionPerformed

    private void jButton_menu_compras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_compras1ActionPerformed
        gerarPdfEstoque();
    }//GEN-LAST:event_jButton_menu_compras1ActionPerformed

    private void jButton_menu_estoque1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_estoque1ActionPerformed
        gerarPdfsSaida();
    }//GEN-LAST:event_jButton_menu_estoque1ActionPerformed

    private void jButton_menu_relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_relatoriosActionPerformed
        gerarPdfPedido();
    }//GEN-LAST:event_jButton_menu_relatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton_menu_categorias;
    private javax.swing.JButton jButton_menu_clientes;
    private javax.swing.JButton jButton_menu_compras;
    private javax.swing.JButton jButton_menu_compras1;
    private javax.swing.JButton jButton_menu_estoque;
    private javax.swing.JButton jButton_menu_estoque1;
    private javax.swing.JButton jButton_menu_fornecedor;
    private javax.swing.JButton jButton_menu_manterusuario;
    private javax.swing.JButton jButton_menu_produtos;
    private javax.swing.JButton jButton_menu_relatorios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private void gerarPdfsPedido() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
