/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Categorias;
import model.bean.Fornecedores;
import model.bean.Produtos;
import model.dao.CategoriaDao;
import model.dao.FornecedorDao;
import model.dao.ProdutoDao;

/**
 *
 * @author Naine
 */
public class TelaManterProdutos extends javax.swing.JFrame {
    Produtos produto = new Produtos();
    ProdutoDao dao= new ProdutoDao();
    
    /**
     * Creates new form TelaProdutos
     */
    public TelaManterProdutos() {
        initComponents();
        CategoriaDao cdao =new CategoriaDao();
    for (Categorias c : cdao.read()) {
        jComboBox_categoria.addItem(c);
        }
    
        DefaultTableModel modelo = (DefaultTableModel) jProdutos.getModel();
        jProdutos.setRowSorter(new TableRowSorter(modelo));
        readjTable();
    }
    public void readjTable() {
        DefaultTableModel modelo = (DefaultTableModel) jProdutos.getModel();
        modelo.setNumRows(0);
        ProdutoDao pdao = new ProdutoDao();

        for (Produtos p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getCodigo_produto(),
                p.getDescricao_produto(),
                p.getCategoria(),
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_produtos_descricao = new javax.swing.JTextField();
        jButton_produtos_cadastrar = new javax.swing.JButton();
        jButton_produtos_alterar = new javax.swing.JButton();
        jButton_produtos_excluir = new javax.swing.JButton();
        jComboBox_categoria = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txt_produtos_codigo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jProdutos = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("CADASTRAR PRODUTOS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Descrição:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Categoria:");

        jButton_produtos_cadastrar.setBackground(new java.awt.Color(102, 102, 255));
        jButton_produtos_cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_produtos_cadastrar.setText("CADASTRAR");
        jButton_produtos_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_produtos_cadastrarActionPerformed(evt);
            }
        });

        jButton_produtos_alterar.setBackground(new java.awt.Color(102, 102, 255));
        jButton_produtos_alterar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_produtos_alterar.setText("ALTERAR");
        jButton_produtos_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_produtos_alterarActionPerformed(evt);
            }
        });

        jButton_produtos_excluir.setBackground(new java.awt.Color(102, 0, 0));
        jButton_produtos_excluir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_produtos_excluir.setText("EXCLUIR");
        jButton_produtos_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_produtos_excluirActionPerformed(evt);
            }
        });

        jComboBox_categoria.setToolTipText("");
        jComboBox_categoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_categoriaItemStateChanged(evt);
            }
        });
        jComboBox_categoria.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jComboBox_categoriaComponentResized(evt);
            }
        });
        jComboBox_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_categoriaActionPerformed(evt);
            }
        });
        jComboBox_categoria.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox_categoriaPropertyChange(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Código:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 0, 0));
        jLabel14.setText("EPOS");

        jButton4.setForeground(new java.awt.Color(240, 240, 240));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/home (1).png"))); // NOI18N
        jButton4.setAlignmentY(0.0F);
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton4.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton4.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton4.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jProdutos.setForeground(new java.awt.Color(0, 0, 0));
        jProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CÓDIGO", "DESCRIÇÃO", "CATEGORIA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProdutos.setName(""); // NOI18N
        jProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jProdutosMouseClicked(evt);
            }
        });
        jProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jProdutosKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_produtos_cadastrar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_produtos_alterar)
                                        .addGap(118, 118, 118)
                                        .addComponent(jButton_produtos_excluir))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_produtos_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(34, 34, 34)
                                                .addComponent(txt_produtos_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(137, 137, 137))
                                    .addComponent(jScrollPane3))))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_produtos_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_produtos_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_produtos_alterar)
                        .addComponent(jButton_produtos_cadastrar))
                    .addComponent(jButton_produtos_excluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_categoriaActionPerformed
        
    }//GEN-LAST:event_jComboBox_categoriaActionPerformed

    private void jButton_produtos_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_produtos_cadastrarActionPerformed
       produto.setCodigo_produto(txt_produtos_codigo.getText());
       produto.setCategoria((Categorias) jComboBox_categoria.getSelectedItem());
       produto.setDescricao_produto(txt_produtos_descricao.getText());
       //produto.setFornecedor(jComboBox_fornecedor);
       
      dao.create(produto);
        
       txt_produtos_codigo.setText("");
       txt_produtos_descricao.setText("");

        
       readjTable();
       
       
    }//GEN-LAST:event_jButton_produtos_cadastrarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new TelaMenu().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProdutosMouseClicked
        if (jProdutos.getSelectedRow() != -1) {

            txt_produtos_codigo.setText(jProdutos.getValueAt(jProdutos.getSelectedRow(), 0).toString());
            txt_produtos_descricao.setText(jProdutos.getValueAt(jProdutos.getSelectedRow(), 1).toString());
            jComboBox_categoria.setSelectedItem(jProdutos.getValueAt(jProdutos.getSelectedRow(), 2).toString());
            

        }
    }//GEN-LAST:event_jProdutosMouseClicked

    private void jProdutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jProdutosKeyReleased
        if (jProdutos.getSelectedRow() != -1) {

            txt_produtos_codigo.setText(jProdutos.getValueAt(jProdutos.getSelectedRow(), 0).toString());
            txt_produtos_descricao.setText(jProdutos.getValueAt(jProdutos.getSelectedRow(), 1).toString());
            jComboBox_categoria.setSelectedItem(jProdutos.getValueAt(jProdutos.getSelectedRow(), 2).toString());

        }
    }//GEN-LAST:event_jProdutosKeyReleased

    private void jComboBox_categoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_categoriaItemStateChanged
        
    }//GEN-LAST:event_jComboBox_categoriaItemStateChanged

    private void jButton_produtos_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_produtos_alterarActionPerformed
       produto.setCodigo_produto(txt_produtos_codigo.getText());
              produto.setDescricao_produto(txt_produtos_descricao.getText());
       produto.setCategoria((Categorias) jComboBox_categoria.getSelectedItem());


       //produto.setFornecedor(jComboBox_fornecedor);
       
      dao.update(produto);
        
       txt_produtos_codigo.setText("");
       txt_produtos_descricao.setText("");

        
       readjTable();
    }//GEN-LAST:event_jButton_produtos_alterarActionPerformed

    private void jButton_produtos_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_produtos_excluirActionPerformed
       produto.setCodigo_produto(txt_produtos_codigo.getText());
       dao.delete(produto);
        
       txt_produtos_codigo.setText("");
       txt_produtos_descricao.setText("");

        
       readjTable();
    }//GEN-LAST:event_jButton_produtos_excluirActionPerformed

    private void jComboBox_categoriaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox_categoriaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_categoriaPropertyChange

    private void jComboBox_categoriaComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboBox_categoriaComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_categoriaComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaManterProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaManterProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaManterProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaManterProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaManterProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_produtos_alterar;
    private javax.swing.JButton jButton_produtos_cadastrar;
    private javax.swing.JButton jButton_produtos_excluir;
    private javax.swing.JComboBox<Object> jComboBox_categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTable jProdutos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_produtos_codigo;
    private javax.swing.JTextField txt_produtos_descricao;
    // End of variables declaration//GEN-END:variables
}
