/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Clientes;
import model.bean.Pedidos;
import model.bean.Produtos;
import model.dao.ClienteDao;
import model.dao.PedidoDao;
import model.dao.ProdutoDao;

/**
 *
 * @author naine
 */
public class TelaPedidos extends javax.swing.JFrame {
    Pedidos pedido = new Pedidos();
    PedidoDao dao= new PedidoDao();
    /**
     * Creates new form TelaPedidos
     */
    public TelaPedidos() {
        initComponents();
        ProdutoDao pdao =new ProdutoDao();
    for (Produtos p : pdao.read()) {
        jComboBox_produto.addItem(p);
        }
    ClienteDao cdao =new ClienteDao();
    for (Clientes c : cdao.read()) {
        jComboBox_cliente.addItem(c);
        }
    DefaultTableModel modelo = (DefaultTableModel) jPedidos.getModel();
        jPedidos.setRowSorter(new TableRowSorter(modelo));
        readjTable();
    }
    
        public void readjTable() {
        DefaultTableModel modelo = (DefaultTableModel) jPedidos.getModel();
        modelo.setNumRows(0);
       
        PedidoDao pedao = new PedidoDao();

        for (Pedidos pe : pedao.read()) {

            modelo.addRow(new Object[]{
                pe.getCod_pedido(),
                pe.getProduto(),
                pe.getCliente(),
                pe.getQtd(),
                pe.getData(),
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_produtos_cadastrar = new javax.swing.JButton();
        jButton_produtos_alterar = new javax.swing.JButton();
        jButton_produtos_excluir = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txt_pedido = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPedidos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_produto = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox_cliente = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txt_qtd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_data = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_produtos_cadastrar.setBackground(new java.awt.Color(102, 102, 255));
        jButton_produtos_cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_produtos_cadastrar.setText("CADASTRAR");
        jButton_produtos_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_produtos_cadastrarActionPerformed(evt);
            }
        });

        jButton_produtos_alterar.setBackground(new java.awt.Color(102, 102, 255));
        jButton_produtos_alterar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_produtos_alterar.setText("ALTERAR");
        jButton_produtos_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_produtos_alterarActionPerformed(evt);
            }
        });

        jButton_produtos_excluir.setBackground(new java.awt.Color(102, 0, 0));
        jButton_produtos_excluir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_produtos_excluir.setText("EXCLUIR");
        jButton_produtos_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_produtos_excluirActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Código:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 0, 0));
        jLabel14.setText("EPOS");

        jButton4.setForeground(new java.awt.Color(240, 240, 240));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/home (1).png"))); // NOI18N
        jButton4.setAlignmentY(0.0F);
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton4.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton4.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton4.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPedidos.setForeground(new java.awt.Color(0, 0, 0));
        jPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "PRODUTO", "CLIENTE", "QUANTIDADE", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPedidos.setName(""); // NOI18N
        jPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPedidosMouseClicked(evt);
            }
        });
        jPedidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPedidosKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jPedidos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("PEDIDOS");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Produto:");

        jComboBox_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_produtoActionPerformed(evt);
            }
        });
        jComboBox_produto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox_produtoPropertyChange(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Cliente:");

        jComboBox_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_clienteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Quantidade:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Data:");

        try {
            txt_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(27, 27, 27)
                                        .addComponent(jComboBox_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton_produtos_cadastrar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton_produtos_alterar)
                                            .addGap(103, 103, 103)
                                            .addComponent(jButton_produtos_excluir))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel10))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jComboBox_produto, 0, 126, Short.MAX_VALUE)
                                                .addComponent(txt_pedido))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addGap(6, 6, 6)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txt_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(243, 243, 243))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jComboBox_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_produtos_alterar)
                    .addComponent(jButton_produtos_cadastrar)
                    .addComponent(jButton_produtos_excluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel14)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_produtos_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_produtos_cadastrarActionPerformed
        pedido.setCod_pedido(txt_pedido.getText());
        pedido.setProduto((Produtos) jComboBox_produto.getSelectedItem());
        pedido.setCliente((Clientes) jComboBox_cliente.getSelectedItem());
        pedido.setQtd(Integer.parseInt(txt_qtd.getText()));
        pedido.setData(txt_data.getText());
        
        dao.create(pedido);

        txt_pedido.setText("");
        txt_qtd.setText("");
        txt_data.setText("");

        readjTable();

    }//GEN-LAST:event_jButton_produtos_cadastrarActionPerformed

    private void jButton_produtos_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_produtos_alterarActionPerformed
        pedido.setCod_pedido(txt_pedido.getText());
        pedido.setProduto((Produtos) jComboBox_produto.getSelectedItem());
        pedido.setCliente((Clientes) jComboBox_cliente.getSelectedItem());
        pedido.setQtd(Integer.parseInt(txt_qtd.getText()));
        pedido.setData(txt_data.getText());
        
        dao.update(pedido);

        txt_pedido.setText("");
        txt_qtd.setText("");
        txt_data.setText("");

        readjTable();
    }//GEN-LAST:event_jButton_produtos_alterarActionPerformed

    private void jButton_produtos_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_produtos_excluirActionPerformed
        pedido.setCod_pedido(txt_pedido.getText());
        dao.delete(pedido);

        txt_pedido.setText("");
        txt_qtd.setText("");
        txt_data.setText("");

        readjTable();
    }//GEN-LAST:event_jButton_produtos_excluirActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new TelaMenu().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPedidosMouseClicked
        if (jPedidos.getSelectedRow() != -1) {

            txt_pedido.setText(jPedidos.getValueAt(jPedidos.getSelectedRow(), 0).toString());
            jComboBox_produto.setSelectedItem(jPedidos.getValueAt(jPedidos.getSelectedRow(), 1).toString());
            jComboBox_cliente.setSelectedItem(jPedidos.getValueAt(jPedidos.getSelectedRow(), 2).toString());
            txt_qtd.setText(jPedidos.getValueAt(jPedidos.getSelectedRow(), 3).toString());
            txt_data.setText(jPedidos.getValueAt(jPedidos.getSelectedRow(), 4).toString());

        }
    }//GEN-LAST:event_jPedidosMouseClicked

    private void jPedidosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPedidosKeyReleased
        if (jPedidos.getSelectedRow() != -1) {

            txt_pedido.setText(jPedidos.getValueAt(jPedidos.getSelectedRow(), 0).toString());
            jComboBox_produto.setSelectedItem(jPedidos.getValueAt(jPedidos.getSelectedRow(), 1).toString());
            jComboBox_cliente.setSelectedItem(jPedidos.getValueAt(jPedidos.getSelectedRow(), 2).toString());
            txt_qtd.setText(jPedidos.getValueAt(jPedidos.getSelectedRow(), 3).toString());
            txt_data.setText(jPedidos.getValueAt(jPedidos.getSelectedRow(), 4).toString());

        }
    }//GEN-LAST:event_jPedidosKeyReleased

    private void jComboBox_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_produtoActionPerformed

    private void jComboBox_produtoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox_produtoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_produtoPropertyChange

    private void jComboBox_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_clienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_produtos_alterar;
    private javax.swing.JButton jButton_produtos_cadastrar;
    private javax.swing.JButton jButton_produtos_excluir;
    private javax.swing.JComboBox<Object> jComboBox_cliente;
    private javax.swing.JComboBox<Object> jComboBox_produto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTable jPedidos;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JFormattedTextField txt_data;
    private javax.swing.JTextField txt_pedido;
    private javax.swing.JTextField txt_qtd;
    // End of variables declaration//GEN-END:variables
}
