/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Usuario;
import model.dao.UsuarioDao;

/**
 *
 * @author Naine
 */
public class TelaCadastrarUsuario extends javax.swing.JFrame {

    Usuario u = new Usuario();
    UsuarioDao dao = new UsuarioDao();

    public TelaCadastrarUsuario() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jUsuario.getModel();
        jUsuario.setRowSorter(new TableRowSorter(modelo));
        readjTable();
    }
public void readjTable() {
        DefaultTableModel modelo = (DefaultTableModel) jUsuario.getModel();
        modelo.setNumRows(0);
        UsuarioDao udao = new UsuarioDao();

        for (Usuario u : udao.read()) {

            modelo.addRow(new Object[]{
                u.getNome_usuario(),
                u.getLogin(),
                u.getSenha(),
                u.getPerfil(),
            });

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_usuario_nome = new javax.swing.JTextField();
        txt_usuario_login = new javax.swing.JTextField();
        txt_usuario_senha = new javax.swing.JTextField();
        jButton_usuario__cadastrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton_usuario__alterar = new javax.swing.JButton();
        jButton_usuario__excluir = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jRadioButtonAdm = new javax.swing.JRadioButton();
        jRadioButtonPad = new javax.swing.JRadioButton();
        jRadioButtonRes = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jUsuario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("CADASTRAR USUÁRIO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Login:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Senha:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Perfil:");

        txt_usuario_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuario_senhaActionPerformed(evt);
            }
        });

        jButton_usuario__cadastrar.setBackground(new java.awt.Color(102, 102, 255));
        jButton_usuario__cadastrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_usuario__cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_usuario__cadastrar.setText("Cadastrar");
        jButton_usuario__cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_usuario__cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_usuario__cadastrarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("EPOS");

        jButton_usuario__alterar.setBackground(new java.awt.Color(102, 102, 255));
        jButton_usuario__alterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_usuario__alterar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_usuario__alterar.setText("Alterar");
        jButton_usuario__alterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_usuario__alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_usuario__alterarActionPerformed(evt);
            }
        });

        jButton_usuario__excluir.setBackground(new java.awt.Color(102, 0, 0));
        jButton_usuario__excluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_usuario__excluir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_usuario__excluir.setText("Excluir");
        jButton_usuario__excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_usuario__excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_usuario__excluirActionPerformed(evt);
            }
        });

        jButton3.setForeground(new java.awt.Color(240, 240, 240));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/home (1).png"))); // NOI18N
        jButton3.setAlignmentY(0.0F);
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton3.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton3.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton3.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonAdm);
        jRadioButtonAdm.setSelected(true);
        jRadioButtonAdm.setText("Administrador");
        jRadioButtonAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAdmActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonPad);
        jRadioButtonPad.setText("Padrão");
        jRadioButtonPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPadActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonRes);
        jRadioButtonRes.setText("Restrito");
        jRadioButtonRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonResActionPerformed(evt);
            }
        });

        jUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NOME", "LOGIN", "SENHA", "PERFIL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jUsuario.setName(""); // NOI18N
        jUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jUsuarioMouseClicked(evt);
            }
        });
        jUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jUsuarioKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jUsuario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_usuario_nome))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txt_usuario_login))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jRadioButtonAdm)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonPad)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonRes)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_usuario_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_usuario__cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_usuario__alterar)
                        .addGap(72, 72, 72)
                        .addComponent(jButton_usuario__excluir)
                        .addGap(73, 73, 73))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(144, 144, 144))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_usuario_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_usuario_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_usuario_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButtonAdm)
                    .addComponent(jRadioButtonPad)
                    .addComponent(jRadioButtonRes))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_usuario__cadastrar)
                    .addComponent(jButton_usuario__alterar)
                    .addComponent(jButton_usuario__excluir))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton_usuario__cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_usuario__cadastrarActionPerformed

        u.setLogin(txt_usuario_login.getText());
        u.setNome_usuario(txt_usuario_nome.getText());
        u.setSenha(txt_usuario_senha.getText());
        if (jRadioButtonAdm.isSelected()) {
            u.setPerfil("Administrador");

        }
        else if (jRadioButtonPad.isSelected()) {

            u.setPerfil("Usuario Padrao");

        }
        else {

           u.setPerfil("Usuário Restrito");

        }

        dao.create(u);
        
        txt_usuario_login.setText("");
        txt_usuario_nome.setText("");
        txt_usuario_senha.setText("");
        
        readjTable();

        
    }//GEN-LAST:event_jButton_usuario__cadastrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new TelaMenu().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_usuario_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuario_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuario_senhaActionPerformed

    private void jButton_usuario__alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_usuario__alterarActionPerformed
        if (jUsuario.getSelectedRow() != -1) {
        
        u.setLogin(txt_usuario_login.getText());
        u.setNome_usuario(txt_usuario_nome.getText());
        u.setSenha(txt_usuario_senha.getText());
        if (jRadioButtonAdm.isSelected()) {
            u.setPerfil("Administrador");

        }
        else if (jRadioButtonPad.isSelected()) {

            u.setPerfil("Usuario Padrao");

        }
        else {

           u.setPerfil("Usuário Restrito");

        }
        
        dao.update(u);
        
        txt_usuario_login.setText("");
        txt_usuario_nome.setText("");
        txt_usuario_senha.setText("");
        
        readjTable();
        }
    }//GEN-LAST:event_jButton_usuario__alterarActionPerformed

    private void jButton_usuario__excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_usuario__excluirActionPerformed
        if (jUsuario.getSelectedRow() != -1) {
        
        u.setLogin(txt_usuario_login.getText());
        dao.delete(u);
        
        txt_usuario_login.setText("");
        txt_usuario_nome.setText("");
        txt_usuario_senha.setText("");
        
        readjTable();
        }
    }//GEN-LAST:event_jButton_usuario__excluirActionPerformed

    private void jRadioButtonAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAdmActionPerformed


    }//GEN-LAST:event_jRadioButtonAdmActionPerformed

    private void jRadioButtonPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPadActionPerformed

    }//GEN-LAST:event_jRadioButtonPadActionPerformed

    private void jRadioButtonResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonResActionPerformed

    }//GEN-LAST:event_jRadioButtonResActionPerformed

    private void jUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsuarioKeyReleased
    if (jUsuario.getSelectedRow() != -1) {

            txt_usuario_nome.setText(jUsuario.getValueAt(jUsuario.getSelectedRow(), 0).toString());
            txt_usuario_login.setText(jUsuario.getValueAt(jUsuario.getSelectedRow(), 1).toString());
            txt_usuario_senha.setText(jUsuario.getValueAt(jUsuario.getSelectedRow(), 2).toString());

        }
    }//GEN-LAST:event_jUsuarioKeyReleased

    private void jUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUsuarioMouseClicked
       if (jUsuario.getSelectedRow() != -1) {

            txt_usuario_nome.setText(jUsuario.getValueAt(jUsuario.getSelectedRow(), 0).toString());
            txt_usuario_login.setText(jUsuario.getValueAt(jUsuario.getSelectedRow(), 1).toString());
            txt_usuario_senha.setText(jUsuario.getValueAt(jUsuario.getSelectedRow(), 2).toString());

        }
    }//GEN-LAST:event_jUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_usuario__alterar;
    private javax.swing.JButton jButton_usuario__cadastrar;
    private javax.swing.JButton jButton_usuario__excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButtonAdm;
    private javax.swing.JRadioButton jRadioButtonPad;
    private javax.swing.JRadioButton jRadioButtonRes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jUsuario;
    private javax.swing.JTextField txt_usuario_login;
    private javax.swing.JTextField txt_usuario_nome;
    private javax.swing.JTextField txt_usuario_senha;
    // End of variables declaration//GEN-END:variables
}
