/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import model.bean.Fornecedores;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.dao.FornecedorDao;

/**
 *
 * @author Naine
 */
public class TelaManterFornecedor extends javax.swing.JFrame {

    Fornecedores fornecedor = new Fornecedores();
    FornecedorDao dao = new FornecedorDao();

    /**
     * Creates new form TelaManterFornecedor
     */
    public TelaManterFornecedor() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jFornecedor.getModel();
        jFornecedor.setRowSorter(new TableRowSorter(modelo));
        readjTable();
    }
public void readjTable() {
        DefaultTableModel modelo = (DefaultTableModel) jFornecedor.getModel();
        modelo.setNumRows(0);
        FornecedorDao fdao = new FornecedorDao();

        for (Fornecedores f : fdao.read()) {

            modelo.addRow(new Object[]{
                f.getRazao_social(),
                f.getCnpj(),
                f.getNome_fornecedor(),
                f.getInsc_estadual(),
                f.getCep(),
                f.getTelefone(),
            
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_fornecedor_razaosocial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton_fornecedor_cadastrar = new javax.swing.JButton();
        jButton_fornecedor_alterar = new javax.swing.JButton();
        jButton_fornecedor_excluir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_fornecedor_nome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jFornecedor = new javax.swing.JTable();
        txt_forcenedor_cnpj = new javax.swing.JFormattedTextField();
        txt_forcenedor_inscricaoestadual = new javax.swing.JFormattedTextField();
        txt_forcenedor_cep = new javax.swing.JFormattedTextField();
        txt_forcenedor_telefone = new javax.swing.JFormattedTextField();

        jMenu3.setText("MENU");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuBar2.add(jMenu3);
        jMenuBar2.add(jMenu4);

        jMenu5.setText("MENU");
        jMenu5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuBar3.add(jMenu5);
        jMenuBar3.add(jMenu6);

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("CADASTRAR FORNECEDOR");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("*Razão Social:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("*CNPJ:");

        txt_fornecedor_razaosocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fornecedor_razaosocialActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Insc. Estadual: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("CEP:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("*Telefone");

        jButton_fornecedor_cadastrar.setBackground(new java.awt.Color(102, 102, 255));
        jButton_fornecedor_cadastrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_fornecedor_cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_fornecedor_cadastrar.setText("Cadastrar");
        jButton_fornecedor_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_fornecedor_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fornecedor_cadastrarActionPerformed(evt);
            }
        });

        jButton_fornecedor_alterar.setBackground(new java.awt.Color(102, 102, 255));
        jButton_fornecedor_alterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_fornecedor_alterar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_fornecedor_alterar.setText("Alterar");
        jButton_fornecedor_alterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_fornecedor_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fornecedor_alterarActionPerformed(evt);
            }
        });

        jButton_fornecedor_excluir.setBackground(new java.awt.Color(102, 0, 0));
        jButton_fornecedor_excluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_fornecedor_excluir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_fornecedor_excluir.setText("Excluir");
        jButton_fornecedor_excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_fornecedor_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fornecedor_excluirActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("EPOS");

        jButton4.setForeground(new java.awt.Color(240, 240, 240));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/home (1).png"))); // NOI18N
        jButton4.setAlignmentY(0.0F);
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton4.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton4.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton4.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Nome:");

        txt_fornecedor_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fornecedor_nomeActionPerformed(evt);
            }
        });

        jFornecedor.setForeground(new java.awt.Color(0, 0, 0));
        jFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "RAZÃO SOCIAL", "CNPJ", "NOME", "INSC. ESTADUAL", "CEP", "TELEFONE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jFornecedor.setName(""); // NOI18N
        jFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFornecedorMouseClicked(evt);
            }
        });
        jFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFornecedorKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jFornecedor);

        try {
            txt_forcenedor_cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_forcenedor_cnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_forcenedor_cnpjActionPerformed(evt);
            }
        });

        try {
            txt_forcenedor_inscricaoestadual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.#.###.#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txt_forcenedor_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txt_forcenedor_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_forcenedor_inscricaoestadual))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_fornecedor_razaosocial))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_fornecedor_nome)
                                    .addComponent(txt_forcenedor_cnpj)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_forcenedor_cep))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jButton_fornecedor_cadastrar)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_forcenedor_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_fornecedor_alterar)
                                        .addGap(105, 105, 105)
                                        .addComponent(jButton_fornecedor_excluir)))))
                        .addGap(46, 46, 46)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txt_fornecedor_razaosocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_forcenedor_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(txt_fornecedor_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_forcenedor_inscricaoestadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(txt_forcenedor_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_forcenedor_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_fornecedor_cadastrar)
                    .addComponent(jButton_fornecedor_alterar)
                    .addComponent(jButton_fornecedor_excluir))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_fornecedor_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fornecedor_cadastrarActionPerformed
        fornecedor.setCnpj(txt_forcenedor_cnpj.getText());
        fornecedor.setNome_fornecedor(txt_fornecedor_nome.getText());
        fornecedor.setRazao_social(txt_fornecedor_razaosocial.getText());
        fornecedor.setInsc_estadual(txt_forcenedor_inscricaoestadual.getText());
        fornecedor.setCep(txt_forcenedor_cep.getText());
        fornecedor.setTelefone(txt_forcenedor_telefone.getText());

        dao.create(fornecedor);
        
        txt_forcenedor_cep.setText("");
        txt_fornecedor_nome.setText("");
        txt_forcenedor_cnpj.setText("");
        txt_forcenedor_inscricaoestadual.setText("");
        txt_forcenedor_telefone.setText("");
        txt_fornecedor_razaosocial.setText("");
        
        readjTable();

        //Criei esse JOption.Pane apenas para testar se está funcionando certo, pode excluir
        /*JOptionPane.showMessageDialog(null, "Fornecedor: " + fornecedor.getCnpj() + "\n"+ fornecedor.getRazao_social()+ "\n" + 
                fornecedor.getInsc_estadual()+ fornecedor.getCep()+ "\n" + fornecedor.getTelefone()+  "\n" + "Cadastrado!");*/
    }//GEN-LAST:event_jButton_fornecedor_cadastrarActionPerformed

    private void jButton_fornecedor_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fornecedor_alterarActionPerformed
        if (jFornecedor.getSelectedRow() != -1) {
        fornecedor.setCnpj(txt_forcenedor_cnpj.getText());
        fornecedor.setNome_fornecedor(txt_fornecedor_nome.getText());
        fornecedor.setRazao_social(txt_fornecedor_razaosocial.getText());
        fornecedor.setInsc_estadual(txt_forcenedor_inscricaoestadual.getText());
        fornecedor.setCep(txt_forcenedor_cep.getText());
        fornecedor.setTelefone(txt_forcenedor_telefone.getText());

        dao.update(fornecedor);
        
        txt_forcenedor_cep.setText("");
        txt_fornecedor_nome.setText("");
        txt_forcenedor_cnpj.setText("");
        txt_forcenedor_inscricaoestadual.setText("");
        txt_forcenedor_telefone.setText("");
        txt_fornecedor_razaosocial.setText("");
        
        readjTable();
        }
//Criei esse JOption.Pane apenas para testar se está funcionando certo, pode excluir
        /*JOptionPane.showMessageDialog(null, "Fornecedor: " + fornecedor.getCnpj() + "\n"+ fornecedor.getRazao_social()+ "\n" + 
                fornecedor.getInsc_estadual()+ fornecedor.getCep()+ "\n" + fornecedor.getTelefone()+  "\n" + "Alterado!");*/
    }//GEN-LAST:event_jButton_fornecedor_alterarActionPerformed

    private void txt_fornecedor_razaosocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fornecedor_razaosocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fornecedor_razaosocialActionPerformed

    private void jButton_fornecedor_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fornecedor_excluirActionPerformed
       if (jFornecedor.getSelectedRow() != -1) {
        fornecedor.setRazao_social(txt_fornecedor_razaosocial.getText());
        dao.delete(fornecedor);
        
        txt_forcenedor_cep.setText("");
        txt_fornecedor_nome.setText("");
        txt_forcenedor_cnpj.setText("");
        txt_forcenedor_inscricaoestadual.setText("");
        txt_forcenedor_telefone.setText("");
        txt_fornecedor_razaosocial.setText("");
        
        readjTable();
       }
//Criei esse JOption.Pane apenas para testar se está funcionando certo, pode excluir
        /* JOptionPane.showMessageDialog(null, "Fornecedor: " + fornecedor.getCnpj() + "\n" + fornecedor.getRazao_social() + "\n"
                + fornecedor.getInsc_estadual() + fornecedor.getCep() + "\n" + fornecedor.getTelefone() + "\n" + "Excluido!");*/
    }//GEN-LAST:event_jButton_fornecedor_excluirActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new TelaMenu().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_fornecedor_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fornecedor_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fornecedor_nomeActionPerformed

    private void jFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFornecedorKeyReleased
        if (jFornecedor.getSelectedRow() != -1) {

            txt_fornecedor_razaosocial.setText(jFornecedor.getValueAt(jFornecedor.getSelectedRow(), 0).toString());
            txt_forcenedor_cnpj.setText(jFornecedor.getValueAt(jFornecedor.getSelectedRow(), 1).toString());
            txt_fornecedor_nome.setText(jFornecedor.getValueAt(jFornecedor.getSelectedRow(), 2).toString());
            txt_forcenedor_inscricaoestadual.setText(jFornecedor.getValueAt(jFornecedor.getSelectedRow(), 3).toString());
            txt_forcenedor_cep.setText(jFornecedor.getValueAt(jFornecedor.getSelectedRow(), 4).toString());
            txt_forcenedor_telefone.setText(jFornecedor.getValueAt(jFornecedor.getSelectedRow(), 5).toString());
            
        }
    }//GEN-LAST:event_jFornecedorKeyReleased

    private void jFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFornecedorMouseClicked
       if (jFornecedor.getSelectedRow() != -1) {

            txt_fornecedor_razaosocial.setText(jFornecedor.getValueAt(jFornecedor.getSelectedRow(), 0).toString());
            txt_forcenedor_cnpj.setText(jFornecedor.getValueAt(jFornecedor.getSelectedRow(), 1).toString());
            txt_fornecedor_nome.setText(jFornecedor.getValueAt(jFornecedor.getSelectedRow(), 2).toString());
            txt_forcenedor_inscricaoestadual.setText(jFornecedor.getValueAt(jFornecedor.getSelectedRow(), 3).toString());
            txt_forcenedor_cep.setText(jFornecedor.getValueAt(jFornecedor.getSelectedRow(), 4).toString());
            txt_forcenedor_telefone.setText(jFornecedor.getValueAt(jFornecedor.getSelectedRow(), 5).toString());
            
        }
    }//GEN-LAST:event_jFornecedorMouseClicked

    private void txt_forcenedor_cnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_forcenedor_cnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_forcenedor_cnpjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaManterFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaManterFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaManterFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaManterFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaManterFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_fornecedor_alterar;
    private javax.swing.JButton jButton_fornecedor_cadastrar;
    private javax.swing.JButton jButton_fornecedor_excluir;
    private javax.swing.JTable jFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JFormattedTextField txt_forcenedor_cep;
    private javax.swing.JFormattedTextField txt_forcenedor_cnpj;
    private javax.swing.JFormattedTextField txt_forcenedor_inscricaoestadual;
    private javax.swing.JFormattedTextField txt_forcenedor_telefone;
    private javax.swing.JTextField txt_fornecedor_nome;
    private javax.swing.JTextField txt_fornecedor_razaosocial;
    // End of variables declaration//GEN-END:variables
}
