/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Categorias;
import model.dao.CategoriaDao;


/**
 *
 * @author Naine
 */
public class TelaManterCategorias extends javax.swing.JFrame {

    Categorias c = new Categorias();
    CategoriaDao dao = new CategoriaDao();
    
    public TelaManterCategorias() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jCategorias.getModel();
        jCategorias.setRowSorter(new TableRowSorter(modelo));
        readjTable();
      
    }
    public void readjTable() {
        DefaultTableModel modelo = (DefaultTableModel) jCategorias.getModel();
        modelo.setNumRows(0);
        CategoriaDao cdao = new CategoriaDao();

        for (Categorias c : cdao.read()) {

            modelo.addRow(new Object[]{
                c.getCodigo_categoria(),
                c.getNome_categoria(),});

        }
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_categoria_nome = new javax.swing.JTextField();
        jButton_cadastrar_categoria = new javax.swing.JButton();
        jButton_Alterar_categoria = new javax.swing.JButton();
        jButton_excluir_categoria = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_categoria_codigo = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jCategorias = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("CADASTRAR CATEGORIAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel2.setText("Código Categoria:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel3.setText("Nome Categoria:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        txt_categoria_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_categoria_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(txt_categoria_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 210, -1));

        jButton_cadastrar_categoria.setBackground(new java.awt.Color(102, 102, 255));
        jButton_cadastrar_categoria.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cadastrar_categoria.setText("Cadastrar");
        jButton_cadastrar_categoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_cadastrar_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cadastrar_categoriaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cadastrar_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jButton_Alterar_categoria.setBackground(new java.awt.Color(102, 102, 255));
        jButton_Alterar_categoria.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Alterar_categoria.setText("Alterar");
        jButton_Alterar_categoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Alterar_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Alterar_categoriaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Alterar_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jButton_excluir_categoria.setBackground(new java.awt.Color(102, 0, 0));
        jButton_excluir_categoria.setForeground(new java.awt.Color(255, 255, 255));
        jButton_excluir_categoria.setText("Excluir");
        jButton_excluir_categoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_excluir_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_excluir_categoriaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_excluir_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("EPOS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));
        getContentPane().add(txt_categoria_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 210, -1));

        jButton6.setForeground(new java.awt.Color(240, 240, 240));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/home (1).png"))); // NOI18N
        jButton6.setAlignmentY(0.0F);
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusPainted(false);
        jButton6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton6.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton6.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton6.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jCategorias.setForeground(new java.awt.Color(0, 0, 0));
        jCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CODIGO", "CATEGORIA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCategorias.setName(""); // NOI18N
        jCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCategoriasMouseClicked(evt);
            }
        });
        jCategorias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCategoriasKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jCategorias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 480, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cadastrar_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cadastrar_categoriaActionPerformed
        c.setCodigo_categoria(txt_categoria_codigo.getText());
        c.setNome_categoria(txt_categoria_nome.getText());
        
        dao.create(c);
        
        txt_categoria_codigo.setText("");
        txt_categoria_nome.setText("");
        
       readjTable();
        
         //Criei esse JOption.Pane apenas para testar se está funcionando certo, pode excluir
        //JOptionPane.showMessageDialog(null, "Categoria: " + categoria.getNome_categoria()+ "\n" + "Cadastrado!");
    }//GEN-LAST:event_jButton_cadastrar_categoriaActionPerformed

    private void jButton_Alterar_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Alterar_categoriaActionPerformed
        
        if (jCategorias.getSelectedRow() != -1) {
        c.setCodigo_categoria(txt_categoria_codigo.getText());
        c.setNome_categoria(txt_categoria_nome.getText());
        
        dao.update(c);
        
        txt_categoria_codigo.setText("");
        txt_categoria_nome.setText("");
        
        readjTable();
         }
    }//GEN-LAST:event_jButton_Alterar_categoriaActionPerformed

    private void jButton_excluir_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_excluir_categoriaActionPerformed
        if (jCategorias.getSelectedRow() != -1) {
        c.setCodigo_categoria(txt_categoria_codigo.getText());
        
        dao.delete(c);
        
        txt_categoria_codigo.setText("");
        txt_categoria_nome.setText("");
        
        readjTable();
        }
    }//GEN-LAST:event_jButton_excluir_categoriaActionPerformed

    private void txt_categoria_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_categoria_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_categoria_nomeActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new TelaMenu().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jCategoriasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCategoriasKeyReleased
        // TODO add your handling code here:
        if (jCategorias.getSelectedRow() != -1) {

            txt_categoria_codigo.setText(jCategorias.getValueAt(jCategorias.getSelectedRow(), 0).toString());
            txt_categoria_nome.setText(jCategorias.getValueAt(jCategorias.getSelectedRow(), 1).toString());

        }
    }//GEN-LAST:event_jCategoriasKeyReleased

    private void jCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCategoriasMouseClicked
        if (jCategorias.getSelectedRow() != -1) {

            txt_categoria_codigo.setText(jCategorias.getValueAt(jCategorias.getSelectedRow(), 0).toString());
            txt_categoria_nome.setText(jCategorias.getValueAt(jCategorias.getSelectedRow(), 1).toString());

        }
    }//GEN-LAST:event_jCategoriasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaManterCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaManterCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaManterCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaManterCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaManterCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton_Alterar_categoria;
    private javax.swing.JButton jButton_cadastrar_categoria;
    private javax.swing.JButton jButton_excluir_categoria;
    private javax.swing.JTable jCategorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_categoria_codigo;
    private javax.swing.JTextField txt_categoria_nome;
    // End of variables declaration//GEN-END:variables

  
}